[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson
  links2004/WebSockets
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
